[[events]]
name = "Generic"
layers = [
    { id = "background", image = "backgrounds/generic_day.png", position = "center" }
]

[[cosmetics]]
name = "CA Star"
layers = [
    { id = "cosmetic", image = "icons/ca_star.png", position = "top-left", scale_y = 0.2, offset_x = 2.5 }
]

[[cosmetics]]
name = "Shiny"
layers = [
    { id = "cosmetic", image = "icons/shiny.png", position = "top-left", scale_y = 0.2, offset_x = 2.5 }
]

[[pokemon_layers]]
layers = [
    { position = "center" }
]

[[pokemon_layers]]
layers = [
    { position = "center", scale_y = 0.6, offset_x = -0.4 },
    { position = "center", scale_y = 0.6, offset_x = 0.4 }
]

[[pokemon_layers]]
layers = [
    { position = "center", scale_y = 0.6, offset_y = -0.4 },
    { position = "center", scale_y = 0.6, offset_x = 0.4, offset_y = 0.4 },
    { position = "center", scale_y = 0.6, offset_x = -0.4, offset_y = 0.4 }
]

[[pokemon_layers]]
layers = [
    { position = "center", scale_y = 0.6, offset_x = -0.4, offset_y = -0.4 },
    { position = "center", scale_y = 0.6, offset_x = -0.4, offset_y = -0.4 },
    { position = "center", scale_y = 0.6, offset_x = 0.4, offset_y = 0.4 },
    { position = "center", scale_y = 0.6, offset_x = -0.4, offset_y = 0.4 }
]