[[events]]
name = "Generic"
background = "generic_day.png"
background_icon = ""
background_icon_scale = 1.0
pokemon_scale = 1.0

[[events]]
name = "Spotlight Hour"
background = "spotlight_hour.png"
background_icon = ""
background_icon_scale = 1.0
pokemon_scale = 1.0

[[events]]
name = "Raid"
background = "generic_day.png"
background_icon = "raid.png"
background_icon_scale = 1.0
pokemon_scale = 1.0

[[events]]
name = "Mega Raid"
background = "generic_day.png"
background_icon = "mega_raid.png"
background_icon_scale = 1.0
pokemon_scale = 1.0

[[events]]
name = "Shadow Raid"
background = "generic_day.png"
background_icon = "shadow_raid.png"
background_icon_scale = 1.0
pokemon_scale = 1.0

[[events]]
name = "Max Raid"
background = "generic_day.png"
background_icon = "max_raid.png"
background_icon_scale = 1.0
pokemon_scale = 1.0

[[events]]
name = "Community Day"
background = "community_day.png"
background_icon = ""
background_icon_scale = 1.0
pokemon_scale = 1.0

[[events]]
name = "Hatch Day"
background = "generic_day.png"
background_icon = "2km_egg.png"
background_icon_scale = 1.0
pokemon_scale = 1.0

[[cosmetics]]
name = "CA Star"
image = "ca_star.png"
scale = 0.3

[[cosmetics]]
name = "Shiny"
image = "shiny.png"
scale = 0.3
